### ISSUE TITLE
opencv-contrib-python==4.3.0.36 is yanked

### ISSUE THREAD

**Issue by chenzuoli** [AIGC-Audio/AudioGPT#54]
i run the command `pip install requirements.txt`
and got an error:
ERROR: No matching distribution found for opencv-contrib-python==4.3.0.36

**Comment by lkraider** [comment]
I've replaced it with a newer version of opencv on my macos 12 in `requirements.txt` and it seems to load fine (although there are other problems with the project checkout/checkpoints still):
```
#opencv-contrib-python==4.3.0.36
opencv-contrib-python~=4.5.0
```

**Comment by idebroy** [comment]
I am also having the same issue in MacOs, I replaced with 
opencv-contrib-python==4.4.0.46

But still getting the following error and stuck. 

            compile options: '-DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/umath -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/npymath -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/indroniel/miniconda3/include/python3.10 -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/common -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/npymath -c'
            extra options: '-faltivec -I/System/Library/Frameworks/vecLib.framework/Headers'
            clang: numpy/core/src/multiarray/alloc.c
            clang: numpy/core/src/multiarray/array_assign_scalar.c
            clang: numpy/core/src/multiarray/buffer.c
            clang: numpy/core/src/multiarray/common.c
            clang: numpy/core/src/multiarray/datetime_strings.c
            clang: numpy/core/src/multiarray/descriptor.c
            clang: build/src.macosx-11.1-arm64-3.10/numpy/core/src/multiarray/einsum.c
            clang: numpy/core/src/multiarray/conversion_utils.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: build/src.macosx-11.1-arm64-3.10/numpy/core/src/multiarray/lowlevel_strided_loops.c
            clang: numpy/core/src/multiarray/multiarraymodule.c
            clang: numpy/core/src/multiarray/nditer_constr.c
            clang: numpy/core/src/multiarray/hashdescr.c
            clang: numpy/core/src/multiarray/refcount.c
            clang: numpy/core/src/multiarray/scalarapi.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/multiarray/temp_elide.c
            clang: numpy/core/src/multiarray/vdot.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: build/src.macosx-11.1-arm64-3.10/numpy/core/src/umath/loops.c
            clang: numpy/core/src/umath/ufunc_type_resolution.c
            clang: numpy/core/src/umath/ufunc_object.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/common/array_assign.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: numpy/core/src/common/ucsnarrow.c
            clang: build/src.macosx-11.1-arm64-3.10/numpy/core/src/common/npy_cpu_features.c
            clang: /private/var/folders/h3/rwc9brxd1qzbf8_yckfd6s280000gq/T/pip-install-dk3ypcye/numpy_ad56aa48a3e44fdbb8e508c6b667c2df/numpy/_build_utils/src/apple_sgemv_fix.c
            clang: build/src.macosx-11.1-arm64-3.10/numpy/core/src/npymath/ieee754.c
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitlyerror:
            the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            clang: error: the clang compiler does not support 'faltivec', please use -maltivec and include altivec.h explicitly
            error: Command "clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /Users/indroniel/miniconda3/include -arch arm64 -fPIC -O2 -isystem /Users/indroniel/miniconda3/include -arch arm64 -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -DNO_ATLAS_INFO=3 -DHAVE_CBLAS -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/umath -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/npymath -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/indroniel/miniconda3/include/python3.10 -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/common -Ibuild/src.macosx-11.1-arm64-3.10/numpy/core/src/npymath -c numpy/core/src/multiarray/buffer.c -o build/temp.macosx-11.1-arm64-3.10/numpy/core/src/multiarray/buffer.o -MMD -MF build/temp.macosx-11.1-arm64-3.10/numpy/core/src/multiarray/buffer.o.d -faltivec -I/System/Library/Frameworks/vecLib.framework/Headers" failed with exit status 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

**Comment by jjnyx** [comment]
I know this issue is closed but has anyone resolved the following issue with numpy?
