### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by NK990** [AIGC-Audio/AudioGPT#63]
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

`+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:07:00.0 Off |                    0 |
| N/A   36C    P0    24W / 250W |      4MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
`

**Comment by hsm207** [comment]
See #43

**Comment by NK990** [comment]
Changed cuda:1 to cuda:0

**Comment by yosun** [comment]
where exactly do you change this?

**Comment by hsm207** [comment]
> where exactly do you change this?

here: https://github.com/AIGC-Audio/AudioGPT/pull/43/files

**Comment by Dawit-Balkew** [comment]
the same error in google colab how to fix it please help me
